version: 0.0
os: linux
files:
  - source: webapp/
    destination: /var/www/html

hooks:
  BeforeInstall:
    - location: webapp/scripts/install_dependencies.sh
      timeout: 300
  ApplicationStart:
    - location: webapp/scripts/start_server.sh
      timeout: 300

